### ISSUE TITLE
Help. Installation errors

### ISSUE THREAD

**Issue by jmulet** [h5p/h5p-math-display#2]
Hi,
I am having some troubles to install this library to h5p in moodle3.6. We are running version 1.17.2 of the plugin hvp for Moodle.

Probably I don't follow the correct steps to install de library. Let me explain the steps I follow:

Administration / ► Plugins / ► Activity modules / ► H5P / ► Libraries H5P

When I upload the zip file download from this repository I get this error:

> File "LICENSE" not allowed. Only files with the following extensions are allowed: json png jpg jpeg gif bmp tif tiff svg eot ttf woff woff2 otf webm mp4 ogg mp3 m4a wav txt pdf rtf doc docx xls xlsx ppt pptx odt ods odp xml csv diff patch swf md textile vtt webvtt js css.

I have tried to unzip the repository and get rid of LICENSE and README. Then, another error appears; "the name of the file does not match the major version". I have also tried to change the name of the zip to H5P.MathDisplay. In that case another error appears, 

> Some files ({$a}->wrongfiles}) cannot be upload. Only files of type .h5p are allowed

I would appreciate very much if you could help me in the installation of this extension.

Josep

**Comment by otacke** [comment]
Hi Josep!

The zip file is not an h5p library that you can install. Repositories on github usually contain source files that need to be built and packed, but not distribution files. You will [find a link to a pre-built-and-packed version on the documentation page](https://h5p.org/mathematical-expressions) for mathematical expressions in H5P.

Best
Oliver

**Comment by jmulet** [comment]
Hi Oliver,
Thank you very much for your swift answer.
Now everything works flawlessly.
Best regards,
Josep

**Comment by otacke** [comment]
@jmulet You're welcome. What's a community for if not for help ...

**Comment by pjotrsavitski** [comment]
The link is not pointing to a 1.0.4 version that has been superseeded by 1.0.5. Attaching the .h5p file to a tagged version within this repository would be a more viable solution.

**Comment by otacke** [comment]
@pjotrsavitski I assume you're hinting to the link on https://h5p.org/mathematical-expressions and I suggest to comment there as the issue is neither related to this very issue here nor to this repository itself.

**Comment by pjotrsavitski** [comment]
@otacke Yes, that is what I meant. Sorry for comment being a bit off-topic and rather harsh. I will try to add a comment to that page later on.

In the meantime, I've build the package with `h5p` utility script from the current state of the repo (master branch) that corresponds to the version 1.0.5. The repo only had some modifications to the markdown file so it should be functionally the same as the latest tagged version. Just change extension from .zip to .h5p and it should work like a charm.
[h5p-math-display-1.0.5.zip](https://github.com/h5p/h5p-math-display/files/3530321/h5p-math-display-1.0.5.zip)

**Comment by otacke** [comment]
Hi @pjotrsavitski !
I think @fnoks will build the package himself, but if someone wants to use your version meanwhile: it's looking good (although the README file is not necessary - I'll add it to the list of files that the cli tool should ignore)!

**Comment by fnoks** [comment]
Thanks for letting me know. I have uploaded 1.0.5 to https://h5p.org/mathematical-expressions
