### ISSUE TITLE
Location of mathdisplay.js in Moodle?

### ISSUE THREAD

**Issue by PhilippImhof** [h5p/h5p-math-display#5]
While trying to contribute w.r.t. https://github.com/h5p/h5p-math-display/issues/4 I realized that I could not find `mathdisplay.js` for my installation.

The only occurrence was in `moodledata/temp`. However, the library list shows MathDisplay (1.0.5) as installed.  I would expect that file to be in `mod/hvp/library`.

Any guidance is appreciated.

**Comment by otacke** [comment]
@PhilippImhof `mod/hvp/library` is used for the plugin itself, but not for the optional libraries that you dynamically add after installing the plugin itself. Those are/(have to be) stored in the hashed depths of the `moodledata` folder.

**Comment by PhilippImhof** [comment]
Thanks again for your help. Would you mind explaining **why** they have to be stored in such an obscure location?

**Comment by otacke** [comment]
@PhilippImhof I fear that someone of the core team will have to answer that question. My moodle coding experience is virtually non-existant. My best guess is that plugins themselves can't write into the plugin folder in order to add individual content libraries, so moodledata had to be used.

**Comment by PhilippImhof** [comment]
That sounds plausible. If it is indeed the case, it might change as soon as H5P is integrated into Moodle's core. I will wait and see before investigating any further. Thank you very much for your support.
